kind: pipeline

steps:
- name: compile
  image: microsoft/dotnet:sdk
  commands:
    - sh build.sh
- name: build-image
  image: plugins/docker
  settings:
    username: apooravsingh
    password: 0c4a34ac-6cfb-48f2-b3cb-ee4fcc73bf0d  
    repo: apooravsingh/dotnetcore-container
    dockerfile: Web/Dockerfile
