kind: pipeline

steps:
- name: compile
  image: microsoft/aspnetcore-build
  command:
  - sh build.sh
- name: build-image:
  image: microsoft/aspnetcore-build
  command:
  - docker build -t dinorows/dotnetcore-container ./Web
