pipeline:
    compile:
        image: microsoft/aspnetcore-build
        commands:
            - sh build.sh
    build-image:
        command:
            - docker build -t apooravsingh/dotnetcore-container ./Web
